"""Derive the ASEJ bibliography from the long-format one.

Two journal-mandated changes, both of which also buy page budget:
  * journal/booktitle names abbreviated per ISO4 / LTWA (an explicit ASEJ rule);
  * doi and url fields dropped, matching the reference examples in the guide.
Over 55 entries this is worth roughly a full page of the two-column manuscript.
"""
import re
from pathlib import Path

SRC = Path(r"C:\Users\user\Desktop\HVAC_DRL_MORL\docs\paper_asej\references_full.bib")
DST = Path(r"C:\Users\user\Desktop\HVAC_DRL_MORL\docs\paper_asej\references_asej.bib")

ABBREV = {
    "Journal of Building Engineering": "J. Build. Eng.",
    "Applied Energy": "Appl. Energy",
    "Energy and Buildings": "Energy Build.",
    "Neural Computing and Applications": "Neural Comput. Appl.",
    "Journal of Building Performance Simulation": "J. Build. Perform. Simul.",
    "Renewable and Sustainable Energy Reviews": "Renew. Sustain. Energy Rev.",
    "Scientific Reports": "Sci. Rep.",
    "Journal of Machine Learning Research": "J. Mach. Learn. Res.",
    "Journal of Artificial Intelligence Research": "J. Artif. Intell. Res.",
    "Autonomous Agents and Multi-Agent Systems": "Auton. Agent. Multi-Agent Syst.",
    "Journal of Computational Physics": "J. Comput. Phys.",
    "IEEE Transactions on Knowledge and Data Engineering": "IEEE Trans. Knowl. Data Eng.",
    "ACM Computing Surveys": "ACM Comput. Surv.",
    "Building Simulation": "Build. Simul.",
    "Nature Machine Intelligence": "Nat. Mach. Intell.",
    "ACM SIGART Bulletin": "ACM SIGART Bull.",
    "SIAM Review": "SIAM Rev.",
    "Journal of Global Optimization": "J. Glob. Optim.",
    # conference proceedings
    "Advances in Neural Information Processing Systems (NeurIPS)": "Adv. Neural Inf. Process. Syst.",
    "Advances in Neural Information Processing Systems": "Adv. Neural Inf. Process. Syst.",
    "International Conference on Machine Learning": "Int. Conf. Mach. Learn.",
    "International Conference on Learning Representations (ICLR)": "Int. Conf. Learn. Represent.",
    "International Conference on Learning Representations": "Int. Conf. Learn. Represent.",
    "Proceedings of the AAAI Conference on Artificial Intelligence": "Proc. AAAI Conf. Artif. Intell.",
    "Proceedings of Building Simulation 2021: 17th Conference of\n               IBPSA": "Proc. 17th IBPSA Conf. Build. Simul.",
    "Proceedings of the 2nd Conference on Learning for Dynamics\n               and Control (L4DC)": "Proc. 2nd Conf. Learn. Dyn. Control (L4DC)",
    "Proceedings of the 20th International Conference on Artificial\n               Intelligence and Statistics (AISTATS)": "Proc. 20th Int. Conf. Artif. Intell. Stat. (AISTATS)",
    "IEEE Symposium Series on Computational Intelligence (SSCI)": "IEEE Symp. Ser. Comput. Intell.",
    "Proceedings of the 42nd International Conference on Machine\n               Learning (ICML)": "Proc. 42nd Int. Conf. Mach. Learn. (ICML)",
    "Proceedings of the 6th ACM International Conference on Systems\n               for Energy-Efficient Buildings, Cities, and Transportation\n               (BuildSys)": "Proc. ACM Int. Conf. Syst. Energy-Efficient Build. Cities Transp. (BuildSys)",
}

text = SRC.read_text(encoding="utf-8")

# drop doi/url fields (single-line in this file)
text = re.sub(r"\n\s*(doi|url)\s*=\s*\{[^}]*\},?", "", text, flags=re.I)
# drop series fields: "Vol. 54 of Proceedings of Machine Learning Research" is pure noise here
text = re.sub(r"\n\s*series\s*=\s*\{[^}]*\},?", "", text, flags=re.I)

for full, short in sorted(ABBREV.items(), key=lambda kv: -len(kv[0])):
    text = text.replace(full, short)

# Dataset Shift is a book, not an article in a journal called "MIT Press"
text = text.replace(
    """@article{Quinonero2009DatasetShift,""", """@book{Quinonero2009DatasetShift,""")
text = text.replace(
    """  title   = {Dataset shift in machine learning},
  journal = {MIT Press},""",
    """  title     = {Dataset Shift in Machine Learning},
  publisher = {MIT Press}, address = {Cambridge, MA},""")

header = (
    "% ASEJ bibliography -- GENERATED by scratchpad/make_asej_bib.py from\n"
    "% references_full.bib. Do not hand-edit: regenerate instead.\n"
    "% Journal names are ISO4-abbreviated (journal rule) and doi/url fields are\n"
    "% dropped (matches the guide's reference examples, and saves ~1 page).\n\n")

DST.write_text(header + text, encoding="utf-8")
print("wrote", DST.name, "-", text.count("\n@"), "entries")
