"""Assemble the three standalone Results sections into one Q1 manuscript skeleton.

It (1) strips each section's standalone scaffolding so it can be \\input into a
single paper without duplicating the global front/back matter, and (2) writes a
master ``paper_combined/main_paper.tex`` skeleton with placeholders for the
non-Results sections.

Stripping per section (the unambiguous duplicates of the global manuscript):
  - the document wrapper (preamble, \\begin/\\end{document}) and \\setcounter,
  - the per-section Nomenclature table  -> one global Nomenclature instead,
  - the per-section Limitations subsection -> global Discussion 8.6,
  - the per-section Conclusion subsection  -> global Conclusion (section 9).

NOT auto-removed: the method-bearing subsections (surrogate math, PPO interface,
metrics, adapter spec). Those are woven into the results prose, so relocating
them into the global Methodology (section 3) / Experimental Setup (section 4) is
left as a manual editorial step; see the TODO markers in the master file.

Usage:
    python docs/build_integrated_paper.py
Each generator also accepts ``--integrated`` to (re)write only its own body.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

DOCS = Path(__file__).resolve().parent
SECTIONS = [
    ("results1_digital_twin_overleaf", "Results I body (Block 1, digital-twin fidelity)"),
    ("results2_control_overleaf", "Results II body (Block 2, control utility)"),
    ("results3_transferability_overleaf", "Results III body (Block 3, transferability)"),
]


def strip_to_body(tex: str) -> str:
    """Return an \\input-able body: section content only, with the standalone
    nomenclature/limitations/conclusion scaffolding and the document wrapper /
    \\setcounter removed."""
    # 1. keep only what is between \begin{document} and \end{document}
    body = tex.split(r"\begin{document}", 1)[1].split(r"\end{document}", 1)[0]
    # 2. drop the standalone section-counter offset (master controls numbering)
    body = re.sub(r"\\setcounter\{section\}\{\d+\}\s*", "", body)
    # 3. drop the per-section Nomenclature table (first table; unique caption)
    body = re.sub(
        r"\\begin\{table\}\[[A-Za-z!]+\]\s*\\centering\s*\\small\s*\\caption\{Nomenclature.*?\\end\{table\}\s*",
        "", body, flags=re.DOTALL,
    )
    # 4. drop the per-section Limitations subsection (up to the next subsection)
    body = re.sub(r"\\subsection\{Limitations\}.*?(?=\\subsection\{)", "", body, flags=re.DOTALL)
    # 5. drop the per-section Conclusion subsection (to the end of the body)
    body = re.sub(r"\\subsection\{[^}]*[Cc]onclusion\}.*\Z", "", body, flags=re.DOTALL)
    return body.strip() + "\n"


def write_body(section_dir: str) -> Path:
    d = DOCS / section_dir
    tex = (d / "main.tex").read_text(encoding="utf-8")
    out = d / "section_body.tex"
    header = (
        "% Auto-generated by docs/build_integrated_paper.py -- do not edit by hand.\n"
        "% Standalone scaffolding (preamble, nomenclature, limitations, conclusion,\n"
        "% \\setcounter) stripped for \\input into the combined manuscript.\n"
    )
    out.write_text(header + strip_to_body(tex), encoding="utf-8")
    return out


MASTER = r"""\documentclass[11pt,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{array}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{siunitx}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{subcaption}
\usepackage{float}
\usepackage{placeins}
\usepackage{hyperref}

\geometry{margin=2.0cm}
\graphicspath{{figures/}}
\hypersetup{colorlinks=true, linkcolor=blue!55!black, citecolor=blue!55!black, urlcolor=blue!55!black}
\captionsetup{font=small, labelfont=bf}

% Macros shared by all three Results bodies (their own \newcommand lines were
% stripped with the section preambles).
\newcommand{\RMSE}{\ensuremath{\mathrm{RMSE}}}
\newcommand{\MAE}{\ensuremath{\mathrm{MAE}}}
\newcommand{\Czon}{\ensuremath{C_{\mathrm{zon}}}}
\newcommand{\Tsupply}{\ensuremath{T_{\mathrm{sup}}}}
\newcommand{\That}{\ensuremath{\widehat{T}}}

\title{Predictive Fidelity is Not Control Utility: A Hybrid Surrogate Recipe for
Reinforcement-Learning HVAC Control and Its Pre-registered Transferability}
\author{TODO authors}
\date{}

\begin{document}
\maketitle

\begin{abstract}
TODO abstract.
\end{abstract}

\textbf{Keywords:} TODO; reinforcement learning; HVAC; digital twin; surrogate model; transfer.

\section*{Nomenclature}
TODO consolidated nomenclature (merge the per-section symbol tables from the
standalone Results packages: $m_s$, RMSE$_T$, $\Czon$, $\Tsupply$, $\lambda_T$,
$\lambda_P$, $\rho_C$, $\tau_k$, $\Delta E$, etc.).

\section{Introduction}
\subsection{Motivation}        TODO
\subsection{Gap}               TODO
\subsection{Hypothesis and study design} TODO
\subsection{Results summary}   TODO
\subsection{Contributions}     TODO

\section{Related Work}
\subsection{Deep reinforcement learning and MORL for HVAC control} TODO
\subsection{Surrogate models and digital twins for building simulation} TODO
\subsection{Physics-informed, Neural ODE, and hybrid models} TODO
\subsection{Benchmark environments and building-simulation infrastructure} TODO
\subsection{Predictive information, distribution shift, and transfer gap} TODO
\subsection{Transfer learning and cross-testcase generalization} TODO
\subsection{Research gap and positioning of this paper} TODO

\section{Methodology}
\subsection{Reference environment} TODO
\subsection{Problem formulation}   TODO
\subsection{Surrogate model design}
\subsubsection{Control-oriented surrogate v3} TODO (relocate the v3 architecture/training math from Results I)
\subsubsection{Physically informed surrogate v3.5 and Stage A/B/C calibration} TODO (relocate from Results I)
\subsubsection{Hybrid surrogate and loss coupling} TODO (relocate the hybrid-reward math from Results II)
\subsection{DRL controller} TODO (relocate the PPO interface / reward / observation from Results II)
\subsection{Evaluation protocol and transferability methodology} TODO (relocate metrics/adapter spec from Results III)

\section{Experimental Setup}
\subsection{Testbeds and serving layer} TODO
\subsection{Data generation and preprocessing} TODO
\subsection{Training and calibration workflow} TODO
\subsection{Runtime characteristics} TODO
\subsection{Evaluation protocol and metrics} TODO
\subsection{Statistical and audit protocol} TODO
\subsection{Reproducibility and audit trail} TODO

% ===== Results sections (auto-generated bodies; sections 5, 6, 7) =====
\input{results1_body.tex}
\input{results2_body.tex}
\input{results3_body.tex}

\section{Discussion}
\subsection{Predictive validity vs RL training utility} TODO
\subsection{Controller-family specificity} TODO
\subsection{Transferability boundary} TODO
\subsection{Step-size, first-divergence horizon, and pre-registration discipline} TODO
\subsection{Positioning relative to related work} TODO
\subsection{Threats to validity}\label{ssec:block1-limitations}\label{ssec:b3lim} TODO (absorb the per-section Limitations bullets; these labels also catch the refs that the stripped per-section Limitations used to carry)

\section{Conclusion}
TODO (absorb the per-section conclusions; state Block 4 future work).

\section*{Data availability}
TODO (cite roadmap provenance maps: Sections 3.2, 11.1, 15.7; reports/ and outputs/ artifacts).

\section*{Supplementary Material: Hou and Evins Numerical Artifacts}
TODO (S1--S11 tables).

\end{document}
"""


def main() -> None:
    paper_dir = DOCS / "paper_combined"
    figdir = paper_dir / "figures"
    paper_dir.mkdir(exist_ok=True)
    figdir.mkdir(exist_ok=True)
    header = (
        "% Auto-generated by docs/build_integrated_paper.py -- do not edit by hand.\n"
        "% Standalone scaffolding (preamble, nomenclature, limitations, conclusion,\n"
        "% \\setcounter) stripped for \\input into the combined manuscript.\n"
    )
    n_fig = 0
    for i, (section_dir, _) in enumerate(SECTIONS, start=1):
        d = DOCS / section_dir
        body = header + strip_to_body((d / "main.tex").read_text(encoding="utf-8"))
        # keep a copy in the section folder (for the --integrated flag) ...
        (d / "section_body.tex").write_text(body, encoding="utf-8")
        # ... and a self-contained copy inside the combined bundle
        (paper_dir / f"results{i}_body.tex").write_text(body, encoding="utf-8")
        for pattern in ("*.pdf", "*.png"):
            for fig in (d / "figures").glob(pattern):
                shutil.copy2(fig, figdir / fig.name)
                n_fig += 1
        print(f"Wrote results{i}_body.tex")
    (paper_dir / "main_paper.tex").write_text(MASTER, encoding="utf-8")
    print(f"Wrote {paper_dir / 'main_paper.tex'} (self-contained; {n_fig} figure files copied into figures/)")


if __name__ == "__main__":
    main()
