"""
Conceptual figures for the paper that are NOT autogenerated from CSV
metrics. These are diagrammatic / synthesizing figures: pipeline
overview, C_zon cross-testcase consistency, and Block 3 component
decomposition.

  C1  pipeline_overview              — data → calibration → hybrid
                                       backend → controllers → live
                                       BOPTEST (Methods)
  C2  czon_consistency               — bar chart of C_zon across
                                       bestest_air + 3 hydronic
                                       testcases (Results III)
  C3  component_decomposition        — 2-panel diagnostic of
                                       surrogate-side vs controller-side
                                       transfer outcomes (Results III)

All three are written as PDF (paper) and PNG (slides) into
paper/figures/q1/, alongside the Q1–Q10 autogenerated suite.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrow, FancyBboxPatch, Rectangle

PAPER_DIR = Path(__file__).resolve().parent
OUT_DIR = PAPER_DIR / "figures" / "q1"
OUT_DIR.mkdir(parents=True, exist_ok=True)

PALETTE = {
    "ink": "#1a1a2e",
    "muted": "#9a9a9a",
    "warn": "#c1121f",
    "success": "#0f8a5f",
    "accent": "#f4a261",
    "blue": "#1e6091",
    "light_bg": "#f5f3ee",
    "panel_bg": "#ffffff",
}

plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
    }
)


def _save(fig, name: str) -> None:
    for ext in ("pdf", "png"):
        path = OUT_DIR / f"{name}.{ext}"
        fig.savefig(path)
    plt.close(fig)
    print(f"[OK] wrote {OUT_DIR / name}.pdf + .png")


# ---------------------------------------------------------------------------
# C1 — Pipeline schematic
# ---------------------------------------------------------------------------


def _pipeline_box(ax, x, y, w, h, title, body, color, body_color=None):
    body_color = body_color or "#ffffff"
    box = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.02,rounding_size=0.04",
        linewidth=1.4,
        edgecolor=color,
        facecolor=body_color,
        zorder=2,
    )
    ax.add_patch(box)
    ax.text(
        x + w / 2,
        y + h - 0.06,
        title,
        ha="center",
        va="top",
        fontsize=10,
        fontweight="bold",
        color=color,
        zorder=3,
    )
    ax.text(
        x + w / 2,
        y + h / 2 - 0.05,
        body,
        ha="center",
        va="center",
        fontsize=8.5,
        color=PALETTE["ink"],
        zorder=3,
    )


def _pipeline_arrow(ax, x1, x2, y, color=None):
    color = color or PALETTE["muted"]
    ax.annotate(
        "",
        xy=(x2, y),
        xytext=(x1, y),
        arrowprops=dict(arrowstyle="-|>", color=color, lw=1.6, shrinkA=2, shrinkB=2),
        zorder=4,
    )


def build_pipeline_schematic() -> None:
    fig, ax = plt.subplots(figsize=(11.0, 4.2))
    ax.set_xlim(0, 11)
    ax.set_ylim(0, 4.2)
    ax.set_axis_off()

    # Five primary boxes along the row
    boxes = [
        dict(
            x=0.15,
            title="Data",
            body=(
                "BOPTEST bestest_air\n"
                "~200k transitions\n"
                "15-min step, TMY"
            ),
            color=PALETTE["blue"],
        ),
        dict(
            x=2.35,
            title="Calibration",
            body=(
                "Stage A — preprocess\n"
                "Stage B — identify Czon\n"
                "Stage C — residual fit"
            ),
            color=PALETTE["success"],
        ),
        dict(
            x=4.55,
            title="Hybrid backend",
            body=(
                "v3 = fast training env\n"
                "v3.5 = frozen anchor\n"
                "1787 steps/s (85x)"
            ),
            color=PALETTE["accent"],
        ),
        dict(
            x=6.75,
            title="Controllers",
            body=(
                "Thermostatic PPO\n"
                "HDRL hierarchical\n"
                "17-D MORL preference"
            ),
            color=PALETTE["warn"],
        ),
        dict(
            x=8.95,
            title="Live BOPTEST",
            body=(
                "Frozen policy\n"
                "Peak / typical / yearly\n"
                "ms, energy, RMSE_T"
            ),
            color=PALETTE["ink"],
        ),
    ]

    w, h = 2.0, 2.1
    y_box = 1.5
    centres = []
    for b in boxes:
        _pipeline_box(ax, b["x"], y_box, w, h, b["title"], b["body"], b["color"])
        centres.append(b["x"] + w / 2)

    # Arrows between boxes
    y_arrow = y_box + h / 2
    for i in range(len(boxes) - 1):
        x1 = boxes[i]["x"] + w + 0.05
        x2 = boxes[i + 1]["x"] - 0.05
        _pipeline_arrow(ax, x1, x2, y_arrow)

    # Lambda anchor overlay (v3.5 enters the loss, not the rollout)
    anchor_y = 0.45
    anchor_box = FancyBboxPatch(
        (3.5, anchor_y - 0.05),
        4.5,
        0.55,
        boxstyle="round,pad=0.02,rounding_size=0.05",
        linewidth=1.2,
        edgecolor=PALETTE["accent"],
        facecolor="#fff7e6",
        linestyle="--",
        zorder=2,
    )
    ax.add_patch(anchor_box)
    ax.text(
        3.5 + 4.5 / 2,
        anchor_y + 0.22,
        "Hybrid loss:  L_PPO  +  lambda_temp x (T_v3 - T_v3.5)^2  +  lambda_power x (P_v3 - P_v3.5)^2",
        ha="center",
        va="center",
        fontsize=9,
        color=PALETTE["ink"],
    )

    # Vertical arrow from the Calibration box to the anchor
    ax.annotate(
        "",
        xy=(5.55, anchor_y + 0.5),
        xytext=(5.55, y_box),
        arrowprops=dict(
            arrowstyle="-|>",
            color=PALETTE["accent"],
            lw=1.4,
            linestyle="--",
            shrinkA=2,
            shrinkB=2,
        ),
        zorder=4,
    )

    # Title
    ax.text(
        5.5,
        3.95,
        "Hybrid surrogate pipeline (Block 1 + Block 2)",
        ha="center",
        va="top",
        fontsize=12,
        fontweight="bold",
        color=PALETTE["ink"],
    )

    # Footer caption notes
    ax.text(
        5.5,
        0.15,
        "v3.5 is frozen after Stage A/B/C — enters only the disagreement penalty, never the rollout forward pass.",
        ha="center",
        va="center",
        fontsize=8.5,
        style="italic",
        color=PALETTE["muted"],
    )

    _save(fig, "C1_pipeline_overview")


# ---------------------------------------------------------------------------
# C2 — C_zon consistency across the hydronic family
# ---------------------------------------------------------------------------


def build_czon_consistency() -> None:
    # Numbers reproduced from Section 7 (Results III):
    #   bestest_air canonical:                           4.413e5 J/K
    #   bestest_hydronic_heat_pump, full regime:         8.347e5 J/K (x1.89)
    #   bestest_hydronic, full regime:                   8.622e5 J/K (x1.95)
    #   singlezone_commercial_hydronic, full regime:     8.429e5 J/K (x1.91)
    labels = [
        "bestest_air\n(canonical)",
        "bestest_hydronic\nheat_pump",
        "bestest_hydronic",
        "singlezone_commercial\nhydronic",
    ]
    czon = np.array([4.413, 8.347, 8.622, 8.429])  # x1e5 J/K
    ratios = czon / czon[0]
    is_ref = [True, False, False, False]
    colors = [PALETTE["blue"] if r else PALETTE["accent"] for r in is_ref]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.0))
    fig.subplots_adjust(wspace=0.32)

    # Left: absolute C_zon values
    x_pos = np.arange(len(labels))
    bars = ax1.bar(x_pos, czon, color=colors, edgecolor=PALETTE["ink"], linewidth=0.9)
    for bar, val in zip(bars, czon):
        ax1.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.15,
            f"{val:.3f}",
            ha="center",
            va="bottom",
            fontsize=9,
            color=PALETTE["ink"],
        )
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(labels, fontsize=8.5)
    ax1.set_ylabel("C_zon  (x10^5 J/K)")
    ax1.set_title("(a) Identified zone thermal capacitance", loc="left")
    ax1.set_ylim(0, czon.max() * 1.18)
    ax1.grid(axis="y", alpha=0.25)

    # Right: ratio to bestest_air with mean / CI band
    hydronic_ratios = ratios[1:]
    mean_r = hydronic_ratios.mean()
    std_r = hydronic_ratios.std(ddof=1)
    ax2.axhspan(
        mean_r - std_r,
        mean_r + std_r,
        color=PALETTE["accent"],
        alpha=0.18,
        label=f"hydronic family band  ({mean_r:.2f} +/- {std_r:.2f})",
    )
    ax2.axhline(mean_r, color=PALETTE["accent"], linewidth=1.3)
    ax2.axhline(1.0, color=PALETTE["blue"], linestyle="--", linewidth=1.0)
    ax2.text(
        -0.45,
        1.02,
        "bestest_air reference (=1.00x)",
        fontsize=8.5,
        color=PALETTE["blue"],
    )

    bars2 = ax2.bar(
        x_pos[1:],
        hydronic_ratios,
        color=PALETTE["accent"],
        edgecolor=PALETTE["ink"],
        linewidth=0.9,
        width=0.55,
    )
    for bar, val in zip(bars2, hydronic_ratios):
        ax2.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02,
            f"{val:.2f}x",
            ha="center",
            va="bottom",
            fontsize=9,
            color=PALETTE["ink"],
        )
    ax2.set_xticks(x_pos[1:])
    ax2.set_xticklabels(labels[1:], fontsize=8.5)
    ax2.set_ylabel("ratio  C_zon_target / C_zon_bestest_air")
    ax2.set_title("(b) Hydronic family ratio (full Stage A/B/C)", loc="left")
    ax2.set_ylim(0.0, 2.4)
    ax2.legend(loc="lower right", frameon=False)
    ax2.grid(axis="y", alpha=0.25)

    fig.suptitle(
        "C_zon transfers structurally across the BOPTEST hydronic family  "
        f"(ratio  {mean_r:.2f}  +/-  {std_r:.2f}  on  N = 3)",
        fontsize=12,
        fontweight="bold",
        color=PALETTE["ink"],
        y=1.02,
    )
    _save(fig, "C2_czon_consistency")


# ---------------------------------------------------------------------------
# C3 — Component decomposition
# ---------------------------------------------------------------------------


def build_component_decomposition() -> None:
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.4))
    fig.subplots_adjust(wspace=0.30)

    # Panel (a): surrogate-side RMSE_T improvement under full Stage A/B/C
    testcases = [
        "bestest_hydronic\nheat_pump",
        "bestest_hydronic",
        "singlezone_commercial\nhydronic",
    ]
    rmse_before = np.array([1.421, 2.666, 1.952])
    rmse_after = np.array([0.565, 0.335, 0.238])
    improvement_pct = (1.0 - rmse_after / rmse_before) * 100.0

    x = np.arange(len(testcases))
    width = 0.36
    ax1.bar(
        x - width / 2,
        rmse_before,
        width,
        label="before recalibration",
        color=PALETTE["warn"],
        edgecolor=PALETTE["ink"],
        linewidth=0.9,
    )
    ax1.bar(
        x + width / 2,
        rmse_after,
        width,
        label="after full Stage A/B/C",
        color=PALETTE["success"],
        edgecolor=PALETTE["ink"],
        linewidth=0.9,
    )

    for xi, b, a, imp in zip(x, rmse_before, rmse_after, improvement_pct):
        ax1.text(
            xi,
            max(b, a) + 0.15,
            f"-{imp:.1f}%",
            ha="center",
            va="bottom",
            fontsize=9,
            color=PALETTE["ink"],
            fontweight="bold",
        )
    ax1.set_xticks(x)
    ax1.set_xticklabels(testcases, fontsize=8.5)
    ax1.set_ylabel("temperature RMSE  (deg C)")
    ax1.set_title("(a) Surrogate-side: 3/3 PASS under full Stage A/B/C", loc="left")
    ax1.legend(loc="upper right", frameon=False)
    ax1.set_ylim(0, max(rmse_before) * 1.25)
    ax1.grid(axis="y", alpha=0.25)

    # Panel (b): controller verdict matrix
    verdicts = np.array(
        [
            # rows = testcases, cols = regimes (none, partial, full)
            [0, 0, 0],  # heat_pump        FAIL FAIL FAIL
            [0, 0, 0],  # hydronic         FAIL FAIL FAIL
            [1, 1, 1],  # commercial       THRESHOLD PASS but deployment FAIL
        ]
    )
    # Encode 0=FAIL, 1=THRESHOLD-PASS-only, 2=DEPLOYMENT-PASS (none in Block3)
    color_map = {0: PALETTE["warn"], 1: PALETTE["accent"], 2: PALETTE["success"]}
    label_map = {0: "FAIL\n(deployment)", 1: "THRESHOLD\nPASS only", 2: "DEPLOYMENT\nPASS"}

    ax2.set_xlim(-0.5, 2.5)
    ax2.set_ylim(-0.5, 2.5)
    ax2.set_xticks([0, 1, 2])
    ax2.set_xticklabels(["none", "partial\nStage C", "full\nStage A/B/C"])
    ax2.set_yticks([0, 1, 2])
    ax2.set_yticklabels(
        [
            "singlezone_commercial",
            "bestest_hydronic",
            "bestest_hydronic_heat_pump",
        ]
    )
    # Note: rows top-down; invert to match conventional matrix top-row first
    for i in range(verdicts.shape[0]):
        for j in range(verdicts.shape[1]):
            v = verdicts[verdicts.shape[0] - 1 - i, j]  # invert vertical
            cell = Rectangle(
                (j - 0.45, i - 0.45),
                0.9,
                0.9,
                facecolor=color_map[v],
                edgecolor=PALETTE["ink"],
                linewidth=0.9,
                alpha=0.85,
            )
            ax2.add_patch(cell)
            ax2.text(
                j,
                i,
                label_map[v],
                ha="center",
                va="center",
                fontsize=8.5,
                color="white" if v == 0 else PALETTE["ink"],
                fontweight="bold",
            )
    ax2.set_title(
        "(b) Controller-side: 0/9 deployment-PASS\n"
        "(frozen direct-TSup policy; mechanical hydronic adapter)",
        loc="left",
        fontsize=10,
    )
    ax2.invert_yaxis()
    ax2.spines["top"].set_visible(True)
    ax2.spines["right"].set_visible(True)
    ax2.tick_params(left=False, bottom=False)

    fig.suptitle(
        "Component decomposition of transferability:  surrogate transfers structurally  /  controller does not",
        fontsize=11.5,
        fontweight="bold",
        color=PALETTE["ink"],
        y=1.02,
    )
    _save(fig, "C3_component_decomposition")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    build_pipeline_schematic()
    build_czon_consistency()
    build_component_decomposition()
    print(f"[done] 3 conceptual figures written to {OUT_DIR}")


if __name__ == "__main__":
    main()
